development:
  adapter: postgresql
  encoding: unicode
  database: wishbone_development
  pool: 5
  username: rails
  password: marm0t

test:
  adapter: postgresql
  encoding: unicode
  database: wishbone_test
  pool: 5
  username: rails
  password: marm0t

production:
  adapter: postgresql
  encoding: unicode
  database: wishbone_production
  pool: 5
  username: rails
  password: marm0t
