development:
  adapter: postgresql
  encoding: unicode
  database: wishbone_development
  pool: 5
  username: wishbone
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wishbone_test
  pool: 5
  username: wishbone
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: wishbone_production
  pool: 5
  username: wishbone
  password:
